// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
// SPDX-FileCopyrightText: 2023-2025 Konstantin Herud
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama.parameters;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import lombok.EqualsAndHashCode;
import net.ladenthin.llama.args.CliArg;
import net.ladenthin.llama.args.ModelFlag;
import net.ladenthin.llama.args.ModelOption;
import org.jspecify.annotations.Nullable;

/**
 * Base class for CLI-style parameter builders.
 *
 * <p>Keys are {@link ModelOption} / {@link ModelFlag} constants, never strings: the map is the argv
 * this project hands to llama.cpp's argument parser, which treats an unregistered option as a hard
 * error, so the set of names that can be written has to be closed rather than merely reviewed. The
 * map itself is still keyed by the wire string, because that is what {@link #toArray()} emits.
 *
 * <p>{@code equals}/{@code hashCode} are generated by Lombok over the parameters map.
 * {@code toString} is intentionally handwritten (not Lombok-generated): it emits the
 * accumulated parameters as a space-separated CLI argv-style string that callers can
 * forward to the native CLI. Replacing it with a Lombok field dump would break that
 * consumer contract.
 */
@EqualsAndHashCode
abstract class CliParameters {

    final Map<String, @Nullable String> parameters = new HashMap<>();

    /**
     * Store a scalar value (typically a primitive: int, long, float, double, boolean)
     * for the given option using {@link String#valueOf(Object)} and return this builder
     * typed as the concrete subtype so callers can collapse the
     * {@code parameters.put(...); return this;} pair into a single
     * {@code return putScalar(...);}.
     *
     * @param option the option to set
     * @param value  the scalar value; autoboxed at the call site
     * @param <T>   the concrete subtype of this builder
     * @return this builder
     */
    // Self-typing builder idiom: caller fixes T to its concrete subtype so chained
    // calls return the concrete builder, not CliParameters.
    @SuppressWarnings({"unchecked", "TypeParameterUnusedInFormals"})
    protected final <T extends CliParameters> T putScalar(ModelOption option, Object value) {
        parameters.put(option.getCliOption(), String.valueOf(value));
        return (T) this;
    }

    /**
     * Store the CLI-argument string of the given enum constant for the given option and
     * return this builder typed as the concrete subtype.
     *
     * @param option the option to set
     * @param value  the enum constant; must implement {@link net.ladenthin.llama.args.CliArg}
     * @param <T>   the concrete subtype of this builder
     * @return this builder
     */
    // Self-typing builder idiom — see putScalar above.
    @SuppressWarnings({"unchecked", "TypeParameterUnusedInFormals"})
    protected final <T extends CliParameters> T putEnum(ModelOption option, CliArg value) {
        parameters.put(option.getCliOption(), value.getArgValue());
        return (T) this;
    }

    /**
     * Store an already-rendered argument string for the given option and return this builder typed
     * as the concrete subtype. Distinct from {@link #putScalar} only in intent: the caller has
     * assembled the value itself (a joined list, a {@code name,value} pair, a JSON blob).
     *
     * @param option the option to set
     * @param value  the rendered argument value
     * @param <T>    the concrete subtype of this builder
     * @return this builder
     */
    // Self-typing builder idiom — see putScalar above.
    @SuppressWarnings({"unchecked", "TypeParameterUnusedInFormals"})
    protected final <T extends CliParameters> T putString(ModelOption option, String value) {
        parameters.put(option.getCliOption(), value);
        return (T) this;
    }

    /**
     * Enable a valueless flag: the key is stored with a {@code null} value, which
     * {@code toArray()} renders as the flag alone.
     *
     * @param flag the flag to enable
     */
    protected final void putFlag(ModelFlag flag) {
        parameters.put(flag.getCliFlag(), null);
    }

    /**
     * Remove an option from the active parameter set.
     *
     * @param option the option to clear
     */
    protected final void removeOption(ModelOption option) {
        parameters.remove(option.getCliOption());
    }

    /**
     * Remove a flag from the active parameter set.
     *
     * @param flag the flag to clear
     */
    protected final void removeFlag(ModelFlag flag) {
        parameters.remove(flag.getCliFlag());
    }

    /**
     * Returns whether the given option is currently set.
     *
     * @param option the option to test
     * @return {@code true} if the option carries a value in this builder
     */
    protected final boolean isOptionSet(ModelOption option) {
        return parameters.containsKey(option.getCliOption());
    }

    /**
     * Returns whether the given flag is currently set.
     *
     * @param flag the flag to test
     * @return {@code true} if the flag is enabled in this builder
     */
    protected final boolean isFlagSet(ModelFlag flag) {
        return parameters.containsKey(flag.getCliFlag());
    }

    /**
     * Returns the raw stored value for the given option.
     *
     * @param option the option to read
     * @return the stored value, or {@code null} when unset (or set as a valueless flag)
     */
    protected final @Nullable String getOption(ModelOption option) {
        return parameters.get(option.getCliOption());
    }

    @Override
    public String toString() {
        StringBuilder builder = new StringBuilder();
        for (Map.Entry<String, @Nullable String> entry : parameters.entrySet()) {
            builder.append(entry.getKey()).append(' ');
            String value = entry.getValue();
            if (value != null) {
                builder.append(value).append(' ');
            }
        }
        return builder.toString();
    }

    /**
     * Returns the accumulated parameters as a C-style {@code argv} array.
     *
     * <p>The first element is a placeholder for the program name, followed by alternating
     * argument keys and values (values are omitted for flag-style arguments).
     *
     * @return a fresh argv array suitable for passing to a native CLI parser
     */
    public String[] toArray() {
        // upper bound: 1 program-name slot + 2 entries (key, value) per parameter
        List<String> result = new ArrayList<>(1 + parameters.size() * 2);
        result.add(""); // c args contain the program name as the first argument, so we add an empty entry
        for (Map.Entry<String, @Nullable String> entry : parameters.entrySet()) {
            result.add(entry.getKey());
            String value = entry.getValue();
            if (value != null) {
                result.add(value);
            }
        }
        return result.toArray(new String[0]);
    }
}
