// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
// SPDX-FileCopyrightText: 2023-2025 Konstantin Herud
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama.parameters;

import com.fasterxml.jackson.databind.DeserializationFeature;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.ObjectReader;
import com.fasterxml.jackson.databind.node.ObjectNode;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import java.util.TreeSet;
import lombok.EqualsAndHashCode;
import org.jspecify.annotations.Nullable;

/**
 * Immutable base for JSON-shaped parameter builders.
 *
 * <p>The native server consumes parameters as a JSON object. This type holds an unmodifiable
 * {@code Map<String, String>} whose <strong>every value is exactly one well-formed JSON
 * value</strong> — that invariant is checked on write by {@link #withPut(String, String)} and is
 * what makes {@link #toJson()} safe. Subclasses expose typed {@code withX(...)} methods that
 * delegate to the protected {@link #withScalar} / {@link #withOptionalJson} / {@link #withRaw}
 * helpers; each allocates a fresh map with one entry added or replaced and routes through the
 * abstract {@link #withParameters(Map)} factory hook so the subclass returns its own concrete type.
 *
 * <h2>Why the invariant is checked rather than assumed</h2>
 *
 * <p>The document used to be assembled by string concatenation over this map, so a value was
 * spliced into the body verbatim. Several public setters take a caller-supplied JSON fragment
 * ({@code withJsonSchema}, {@code withResponseFormat}, {@code withStreamOptions},
 * {@code withMessagesJson}, {@code withToolsJson}), and a fragment carrying a top-level comma
 * therefore injected <em>sibling fields</em> into the request rather than only setting its own.
 * Because the native parser resolves duplicate keys last-wins, an injected field silently
 * overrode one the application had already set — a limit such as {@code n_predict} could be
 * raised by whatever produced the fragment. Validating on write makes the malformed input fail
 * at the call site that introduced it, with the offending key named.
 *
 * <p>{@code equals}/{@code hashCode} are generated by Lombok over the {@code parameters} map; the
 * {@code serializer} field is excluded because it is a stateless helper. {@link #toString()} is a
 * <strong>debug</strong> view and deliberately not valid JSON — see its own documentation.
 */
@EqualsAndHashCode
abstract class JsonParameters {

    /**
     * Reader used for both the write-time check and the render. {@code FAIL_ON_TRAILING_TOKENS} is
     * the load-bearing part: plain {@code readTree} parses the first value and <em>ignores</em>
     * whatever follows it, so without this feature a fragment like
     * {@code {"type":"json_object"}, "n_predict": 999999} would be silently truncated to its first
     * object instead of rejected — quiet data loss in place of a clear error.
     */
    private static final ObjectReader STRICT_JSON_READER =
            ParameterJsonSerializer.OBJECT_MAPPER.reader().with(DeserializationFeature.FAIL_ON_TRAILING_TOKENS);

    /** Longest prefix of a rejected value echoed back in the exception message. */
    private static final int REJECTED_VALUE_EXCERPT = 80;

    // Every value is exactly one well-formed JSON value (see withPut). The map is wrapped in
    // Collections.unmodifiableMap by every factory hook so even reflective access cannot mutate
    // stored state.
    final Map<String, String> parameters;

    /** Serializer for converting Java values to JSON-safe strings. */
    @EqualsAndHashCode.Exclude
    protected final ParameterJsonSerializer serializer = new ParameterJsonSerializer();

    /** Construct an empty parameter set. Subclasses chain factories on top of this. */
    protected JsonParameters() {
        this.parameters = Collections.emptyMap();
    }

    /**
     * Wrap a caller-provided map verbatim. The caller is responsible for ensuring the map is
     * already unmodifiable and that every value satisfies the one-JSON-value invariant (the
     * {@code withX} helpers always do both); this constructor does not re-wrap or re-check.
     *
     * @param parameters the pre-built parameter map; must already be unmodifiable
     */
    protected JsonParameters(Map<String, String> parameters) {
        this.parameters = parameters;
    }

    /**
     * Render the request body: a compact JSON object built by Jackson from the accumulated
     * parameters. This is what callers hand to the native server.
     *
     * <p>Keys are emitted in sorted order. JSON objects are unordered, so this changes nothing for
     * the server, but it makes the body reproducible for a given parameter set — the previous
     * hand-rolled renderer walked a {@link HashMap} and produced a different byte sequence from run
     * to run, which is awkward to diff, log or assert on.
     *
     * @return the request body as compact JSON
     */
    public final String toJson() {
        ObjectNode root = ParameterJsonSerializer.OBJECT_MAPPER.createObjectNode();
        for (Map.Entry<String, String> entry : new TreeMap<>(parameters).entrySet()) {
            root.set(entry.getKey(), parseOrThrow(entry.getKey(), entry.getValue()));
        }
        // JsonNode.toString() is Jackson's own compact serialization and throws nothing, so the
        // renderer has no failure path of its own: every node in the tree came out of a successful
        // parse above.
        return root.toString();
    }

    /**
     * Debug representation. <strong>Deliberately not valid JSON</strong>, and deliberately without
     * the values: a parameter set carries the prompt, the message history and any tool definitions,
     * so a log line built from it would leak the whole payload. Use {@link #toJson()} for the wire.
     *
     * <p>The shape is chosen so that a caller who used to pass {@code toString()} to the native
     * layer fails immediately at the JSON parser instead of quietly sending a different body.
     *
     * @return a redacted, non-JSON summary naming the class and the keys that are set
     */
    @Override
    public String toString() {
        return getClass().getSimpleName() + "{keys=" + new TreeSet<>(parameters.keySet()) + ", values=redacted}";
    }

    /**
     * Serialize a non-null string to its JSON string form. Use
     * {@link #withOptionalJson(String, String)} when the input may be null and the
     * caller wants null to behave as "do not set this parameter".
     *
     * @param text the non-null input
     * @return the JSON-encoded string
     */
    String toJsonString(String text) {
        return serializer.toJsonString(text);
    }

    /**
     * Subclass factory hook. Return a new instance of the concrete subtype carrying
     * the supplied (already unmodifiable) parameter map; the existing instance is
     * left untouched.
     *
     * @param newParameters the new parameter map (must already be unmodifiable)
     * @param <T>           the concrete subtype of this parameter set
     * @return a new instance of the concrete subtype
     */
    @SuppressWarnings("TypeParameterUnusedInFormals")
    protected abstract <T extends JsonParameters> T withParameters(Map<String, String> newParameters);

    /**
     * Internal helper that enforces the one-JSON-value invariant, copies the current map, applies
     * one {@code put}, wraps the copy as unmodifiable and routes through
     * {@link #withParameters(Map)}.
     *
     * @throws IllegalArgumentException if {@code value} is not exactly one well-formed JSON value
     */
    @SuppressWarnings("TypeParameterUnusedInFormals")
    private <T extends JsonParameters> T withPut(String key, String value) {
        parseOrThrow(key, value);
        Map<String, String> next = new HashMap<>(parameters);
        next.put(key, value);
        return withParameters(Collections.unmodifiableMap(next));
    }

    /**
     * Parse one stored or incoming value, rejecting anything that is not exactly one well-formed
     * JSON value.
     *
     * @throws IllegalArgumentException with the offending key named, and a bounded excerpt of the
     *     value so a large or hostile fragment cannot flood a log through the message
     */
    private static JsonNode parseOrThrow(String key, String value) {
        try {
            return STRICT_JSON_READER.readTree(value);
        } catch (Exception e) {
            String excerpt = value.length() > REJECTED_VALUE_EXCERPT
                    ? value.substring(0, REJECTED_VALUE_EXCERPT) + "..."
                    : value;
            throw new IllegalArgumentException(
                    key + " must be exactly one well-formed JSON value, but was: " + excerpt, e);
        }
    }

    /**
     * Returns a new parameter set with {@code key} mapped to the given JSON fragment. Used when the
     * caller has already built a JSON value (array, object) externally.
     *
     * <p>The fragment is validated, not trusted: anything that is not exactly one well-formed JSON
     * value — including a well-formed value followed by more text — is rejected.
     *
     * @param key   the parameter key
     * @param value the JSON value
     * @param <T>   the concrete subtype of this parameter set
     * @return a new instance with the entry inserted or replaced
     * @throws IllegalArgumentException if {@code value} is not exactly one well-formed JSON value
     */
    @SuppressWarnings("TypeParameterUnusedInFormals")
    protected final <T extends JsonParameters> T withRaw(String key, String value) {
        return withPut(key, value);
    }

    /**
     * Returns a new parameter set with {@code key} mapped to {@code value} via
     * {@link String#valueOf(Object)}. Used for primitives (int, long, float, double,
     * boolean).
     *
     * @param key   the parameter key
     * @param value the scalar value; autoboxed at the call site
     * @param <T>   the concrete subtype of this parameter set
     * @return a new instance with the entry inserted or replaced
     */
    @SuppressWarnings("TypeParameterUnusedInFormals")
    protected final <T extends JsonParameters> T withScalar(String key, Object value) {
        // String.valueOf on a non-finite float/double yields "NaN"/"Infinity" — invalid JSON tokens
        // the native nlohmann parser rejects. Reject at the source so the caller gets a clear error
        // instead of an opaque downstream failure. Integer/Long are always finite (a no-op here);
        // Boolean is not a Number and is skipped.
        if (value instanceof Number && !Double.isFinite(((Number) value).doubleValue())) {
            throw new IllegalArgumentException(key + " must be a finite number but was " + value);
        }
        return withPut(key, String.valueOf(value));
    }

    /**
     * Conditionally store a JSON-encoded string under {@code key}: when {@code text}
     * is {@code null} the call is a no-op (returns {@code this}); otherwise the value
     * is JSON-encoded and a new instance is returned.
     *
     * @param key  the parameter key
     * @param text the optional input; {@code null} means "leave the parameter unset"
     * @param <T>  the concrete subtype of this parameter set
     * @return {@code this} if {@code text} is null, otherwise a new instance with the entry set
     */
    @SuppressWarnings({"unchecked", "TypeParameterUnusedInFormals"})
    protected final <T extends JsonParameters> T withOptionalJson(String key, @Nullable String text) {
        if (text == null) {
            return (T) this;
        }
        return withPut(key, serializer.toJsonString(text));
    }
}
