// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama.server;

import com.fasterxml.jackson.databind.node.ObjectNode;
import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.net.HttpURLConnection;
import java.net.URI;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.util.List;
import java.util.Optional;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.TimeUnit;
import lombok.EqualsAndHashCode;
import net.ladenthin.llama.json.RouterModelsResponseParser;
import net.ladenthin.llama.value.RouterModel;
import org.jspecify.annotations.Nullable;

/**
 * Typed client for the upstream <em>router mode</em> model-management endpoints
 * ({@code GET /models}, {@code POST /models/load}, {@code POST /models/unload}) — the API a
 * {@link NativeServer} exposes when started with {@code --models-dir} instead of a model
 * (see the README "Router mode" section and {@code patches/0008}).
 *
 * <p>Replaces the raw HTTP+JSON boilerplate callers previously had to write themselves
 * (hand-building request bodies, knowing that a model's lifecycle state lives at
 * {@code status.value}, polling until {@code "loaded"}). Works against the in-JVM
 * {@link NativeServer} or any external {@code llama-server} router alike — it is plain HTTP,
 * no JNI.
 *
 * <pre>{@code
 * NativeServer.setWorkerCommand(javaBin, "-cp", classpath, "net.ladenthin.llama.server.NativeServer");
 * try (NativeServer router = new NativeServer("--models-dir", dir, "--port", "8080").start()) {
 *     RouterClient client = new RouterClient(8080);
 *     List<RouterModel> models = client.listModels();
 *     client.loadModel(models.get(0).getId());
 *     client.awaitModelLoaded(models.get(0).getId(), 240_000L);
 *     // ... POST /v1/chat/completions with {"model": models.get(0).getId(), ...}
 * }
 * }</pre>
 *
 * <p>Instances are immutable and safe to share across threads; every call opens a short-lived
 * {@link HttpURLConnection}.</p>
 *
 * <p><strong>API keys.</strong> Pass one to the {@code apiKey} constructors and every request
 * carries {@code Authorization: Bearer <key>}. A router started with {@code --api-key} needs it for
 * <em>all</em> of these calls: {@code /models/load} and {@code /models/unload} have always been
 * gated, and since llama.cpp <strong>b10519</strong> (upstream #26347 dropped {@code /models} and
 * {@code /v1/models} from the server's public-endpoint set) {@link #listModels()},
 * {@link #findModel(String)} and {@link #awaitModelLoaded(String, long)} are gated too. The
 * key-less constructors remain the right choice for a router started without one.</p>
 *
 * <p>{@code equals}/{@code hashCode} are generated by Lombok over the {@code host}, {@code port}
 * and {@code apiKey} fields (two clients addressing the same router with the same credential
 * compare equal). {@code toString} is intentionally handwritten (not Lombok-generated) so the
 * client renders as its target URL, "{@code RouterClient(http://host:port)}", in log traces &mdash;
 * the key is never printed.</p>
 */
@EqualsAndHashCode
public final class RouterClient {

    /** Poll interval used by {@link #awaitModelLoaded(String, long)}. */
    public static final long POLL_INTERVAL_MILLIS = 500L;

    /** Per-request connect/read timeout for the plain model-management calls. */
    private static final int REQUEST_TIMEOUT_MILLIS = 30_000;

    private static final RouterModelsResponseParser PARSER = new RouterModelsResponseParser();

    /** Loopback address used by the constructors that take no host. */
    private static final String DEFAULT_HOST = "127.0.0.1";

    private final String host;
    private final int port;

    /** Bearer credential sent on every request; {@code null} for an unauthenticated router. */
    private final @Nullable String apiKey;

    /**
     * Client for an unauthenticated router on {@code 127.0.0.1}.
     *
     * @param port the router's HTTP port
     */
    public RouterClient(int port) {
        this(DEFAULT_HOST, port, null);
    }

    /**
     * Client for an unauthenticated router on an arbitrary host.
     *
     * @param host the router's host name or address
     * @param port the router's HTTP port
     */
    public RouterClient(String host, int port) {
        this(host, port, null);
    }

    /**
     * Client for a router on {@code 127.0.0.1} started with {@code --api-key}.
     *
     * @param port the router's HTTP port
     * @param apiKey the key to send as {@code Authorization: Bearer <key>}; {@code null} or empty
     *     sends no header, which is only correct for a router started without {@code --api-key}
     */
    public RouterClient(int port, @Nullable String apiKey) {
        this(DEFAULT_HOST, port, apiKey);
    }

    /**
     * Client for a router on an arbitrary host, optionally authenticated.
     *
     * @param host the router's host name or address
     * @param port the router's HTTP port
     * @param apiKey the key to send as {@code Authorization: Bearer <key>}; {@code null} or empty
     *     sends no header, which is only correct for a router started without {@code --api-key}
     */
    public RouterClient(String host, int port, @Nullable String apiKey) {
        this.host = host;
        this.port = port;
        this.apiKey = apiKey == null || apiKey.isEmpty() ? null : apiKey;
    }

    /**
     * List every model the router knows about ({@code GET /models}), with its lifecycle
     * status and failure marker.
     *
     * @return the model entries, in server order
     * @throws IOException if the request fails or the router answers non-2xx
     */
    public List<RouterModel> listModels() throws IOException {
        return PARSER.parse(request("GET", "/models", null));
    }

    /**
     * Look up a single model by identifier.
     *
     * @param modelId the model identifier (as listed by {@link #listModels()})
     * @return the entry, or {@link Optional#empty()} when the router does not list it
     * @throws IOException if the request fails or the router answers non-2xx
     */
    public Optional<RouterModel> findModel(String modelId) throws IOException {
        for (RouterModel model : listModels()) {
            if (model.getId().equals(modelId)) {
                return Optional.of(model);
            }
        }
        return Optional.empty();
    }

    /**
     * Ask the router to start a worker for {@code modelId} ({@code POST /models/load}).
     * Non-blocking on the server side: the call returns as soon as the load is initiated —
     * use {@link #awaitModelLoaded(String, long)} to wait for readiness.
     *
     * @param modelId the model identifier to load
     * @throws IOException if the request fails or the router rejects it (unknown model,
     *     already running, ...) — the router's error body is included in the message
     */
    public void loadModel(String modelId) throws IOException {
        request("POST", "/models/load", modelBody(modelId));
    }

    /**
     * Ask the router to stop the worker for {@code modelId} ({@code POST /models/unload}).
     *
     * @param modelId the model identifier to unload
     * @throws IOException if the request fails or the router rejects it (unknown model, not
     *     running) — the router's error body is included in the message
     */
    public void unloadModel(String modelId) throws IOException {
        request("POST", "/models/unload", modelBody(modelId));
    }

    /**
     * Poll {@link #listModels()} until {@code modelId} reaches
     * {@link RouterModel.Status#LOADED}, its worker is flagged as failed, or the timeout
     * elapses. Fails fast (instead of running out the timeout) when the router does not list
     * the model or marks it failed.
     *
     * <p><strong>Hidden models cannot be awaited here.</strong> Since llama.cpp b10505 (upstream
     * #27346) the router omits a cache model from {@code GET /models} when a preset with
     * {@code dedup-cache-models} already covers the same file &mdash; upstream's own comment is
     * "hidden from GET /models, but still accept if requested". Such a model loads and serves
     * normally but never appears in the listing, so no amount of polling can observe it and this
     * method throws. Issue the request directly instead: the router resolves a hidden model by
     * name, and with autoload enabled it waits for the worker before proxying. The thrown message
     * names this cause so it is not mistaken for a wrong identifier.</p>
     *
     * @param modelId the model identifier to wait for
     * @param timeoutMillis how long to keep polling
     * @return the entry in its {@code LOADED} state
     * @throws IOException if a poll request fails
     * @throws InterruptedException if the calling thread is interrupted while waiting
     * @throws IllegalStateException if the model is not listed by the router, its worker
     *     failed (exit code included), or the timeout elapses
     */
    public RouterModel awaitModelLoaded(String modelId, long timeoutMillis) throws IOException, InterruptedException {
        long deadline = System.currentTimeMillis() + timeoutMillis;
        RouterModel last = null;
        while (System.currentTimeMillis() < deadline) {
            Optional<RouterModel> model = findModel(modelId);
            if (!model.isPresent()) {
                throw new IllegalStateException("Router does not list model '" + modelId
                        + "' — check --models-dir and the identifier, or, if the model exists, whether a preset "
                        + "with dedup-cache-models hides it from GET /models (a hidden model still loads and "
                        + "serves by name, but cannot be awaited through the listing)");
            }
            last = model.get();
            if (last.isFailed()) {
                throw new IllegalStateException(
                        "Router worker for model '" + modelId + "' failed with exit code " + last.getExitCode());
            }
            if (last.getStatus() == RouterModel.Status.LOADED) {
                return last;
            }
            // Interruptible pause between polls; a latch that is never counted down is the
            // project's Thread.sleep-free wait primitive (see LlamaArchitectureTest#noThreadSleep).
            if (new CountDownLatch(1).await(POLL_INTERVAL_MILLIS, TimeUnit.MILLISECONDS)) {
                throw new IllegalStateException(
                        "unreachable while polling model '" + modelId + "': the poll latch is never counted down");
            }
        }
        throw new IllegalStateException("Model '" + modelId + "' did not reach LOADED within " + timeoutMillis
                + " ms (last status: " + last + ")");
    }

    private static String modelBody(String modelId) {
        ObjectNode body = RouterModelsResponseParser.OBJECT_MAPPER.createObjectNode();
        body.put("model", modelId);
        return body.toString();
    }

    /**
     * Execute one HTTP request and return the response body. Non-2xx responses raise an
     * {@link IOException} carrying the status code and the router's error body (upstream
     * answers with a JSON {@code {"error": ...}} object), so callers see the actual reason.
     */
    private String request(String method, String path, @Nullable String body) throws IOException {
        // URI.create(...).toURL() instead of the URL(String) constructor: the latter is
        // deprecated (no validation/encoding) — flagged by CodeQL; this form is Java-8-safe.
        URL url = URI.create("http://" + host + ":" + port + path).toURL();
        HttpURLConnection connection = (HttpURLConnection) url.openConnection();
        try {
            connection.setRequestMethod(method);
            connection.setConnectTimeout(REQUEST_TIMEOUT_MILLIS);
            connection.setReadTimeout(REQUEST_TIMEOUT_MILLIS);
            if (apiKey != null) {
                connection.setRequestProperty("Authorization", "Bearer " + apiKey);
            }
            if (body != null) {
                connection.setDoOutput(true);
                connection.setRequestProperty("Content-Type", "application/json");
                try (OutputStream out = connection.getOutputStream()) {
                    out.write(body.getBytes(StandardCharsets.UTF_8));
                }
            }
            int code = connection.getResponseCode();
            InputStream stream = code >= 200 && code < 300 ? connection.getInputStream() : connection.getErrorStream();
            String response = readFully(stream);
            if (code < 200 || code >= 300) {
                throw new IOException("Router " + method + " " + path + " answered HTTP " + code + ": " + response);
            }
            return response;
        } finally {
            connection.disconnect();
        }
    }

    @Override
    public String toString() {
        return "RouterClient(http://" + host + ":" + port + ")";
    }

    private static String readFully(@Nullable InputStream stream) throws IOException {
        if (stream == null) {
            return "";
        }
        ByteArrayOutputStream buffer = new ByteArrayOutputStream();
        byte[] chunk = new byte[8192];
        int read;
        while ((read = stream.read(chunk)) != -1) {
            buffer.write(chunk, 0, read);
        }
        return new String(buffer.toByteArray(), StandardCharsets.UTF_8);
    }
}
