# SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
#
# SPDX-License-Identifier: MIT

# Generates a C++ header listing every CLI flag the Java layer can emit into the argv that
# LlamaModel.loadModel() hands to llama.cpp's common_params_parse().
#
# WHY THIS EXISTS
# ---------------
# ModelFlag / ModelParameters are the only two places that write a "--flag" key into the
# parameter map, and that map becomes argv verbatim. common_params_parse() treats an
# *unregistered* option as a hard error, not a warning -- so the moment upstream removes a
# flag (or narrows its set_examples() scope away from LLAMA_EXAMPLE_SERVER), the matching
# builder method silently turns into "this model will never load".
#
# Every Java-side test of these methods asserts the *string mapping* (hasKey("--mlock")), never
# that llama.cpp still accepts the string, so they stay green forever while the flag is dead.
# That is exactly how --mlock/--no-mmap (removed at b10878), --dump-kv-cache, --hf-repo-v and
# --hf-file-v reached main, and how --grp-attn-n/--grp-attn-w hid for even longer: those two
# still exist in arg.cpp, but are scoped to LLAMA_EXAMPLE_COMPLETION, so a grep-based sweep
# reports them alive while the server parser rejects them. A textual check is structurally
# blind to example scoping; only the real parser knows.
#
# So: this script extracts the list from the Java sources (the single source of truth), and
# src/test/cpp/test_model_flags.cpp feeds every entry to the *actual*
# common_params_parser_init(params, LLAMA_EXAMPLE_SERVER) option table. jllama_test runs on
# every platform in the "C++ Tests" job, so a llama.cpp bump that kills a flag reds CI in the
# same run that introduces it.
#
# EXTRACTION
# ----------
# Line-oriented on purpose: any line whose trimmed form starts with "*", "//" or "/*" is a
# comment and is dropped before matching, which removes every Javadoc mention of a flag
# ({@code --flash-attn}, prose referring to --mlock, ...) without needing a real Java parser.
# What survives is `"--something"` in code position -- enum constants, putScalar/putEnum keys,
# parameters.put keys, and the private static final ARG_* constants alike.
#
# Inputs : JAVA_FLAG_SOURCES  - list of .java files to scan
#          OUTPUT_HEADER      - path of the header to write
# Output : a header defining JLLAMA_JAVA_CLI_FLAGS[] / JLLAMA_JAVA_CLI_FLAG_COUNT

function(jllama_extract_java_cli_flags)
    cmake_parse_arguments(ARG "" "OUTPUT_HEADER" "JAVA_FLAG_SOURCES" ${ARGN})

    if(NOT ARG_OUTPUT_HEADER)
        message(FATAL_ERROR "jllama_extract_java_cli_flags: OUTPUT_HEADER is required")
    endif()
    if(NOT ARG_JAVA_FLAG_SOURCES)
        message(FATAL_ERROR "jllama_extract_java_cli_flags: JAVA_FLAG_SOURCES is required")
    endif()

    set(_flags "")
    foreach(_src IN LISTS ARG_JAVA_FLAG_SOURCES)
        if(NOT EXISTS "${_src}")
            message(FATAL_ERROR "jllama_extract_java_cli_flags: missing source ${_src}")
        endif()
        file(STRINGS "${_src}" _lines)
        foreach(_line IN LISTS _lines)
            string(STRIP "${_line}" _trimmed)
            # Drop comment lines (Javadoc continuations, // and block-comment openers).
            if(_trimmed MATCHES "^(\\*|//|/\\*)")
                continue()
            endif()
            # CMake regex has no global match, so consume the line one literal at a time.
            while(_line MATCHES "\"(--[A-Za-z0-9][A-Za-z0-9._+-]*)\"")
                list(APPEND _flags "${CMAKE_MATCH_1}")
                string(REPLACE "\"${CMAKE_MATCH_1}\"" "" _line "${_line}")
            endwhile()
        endforeach()
    endforeach()

    list(REMOVE_DUPLICATES _flags)
    list(SORT _flags)
    list(LENGTH _flags _count)

    # A silently empty list would make the contract test vacuously pass -- the same
    # "nothing to scan reported as a clean pass" trap verify-bytecode-version.sh exits 2 for.
    if(_count LESS 50)
        message(FATAL_ERROR
            "jllama_extract_java_cli_flags: only ${_count} flags extracted from "
            "${ARG_JAVA_FLAG_SOURCES} -- the extractor is broken or the sources moved")
    endif()

    set(_body "")
    foreach(_flag IN LISTS _flags)
        string(APPEND _body "    \"${_flag}\",\n")
    endforeach()

    set(_header "// Generated by cmake/extract-java-cli-flags.cmake -- DO NOT EDIT.\n")
    string(APPEND _header "// Source of truth: the Java files listed in llama/CMakeLists.txt.\n")
    string(APPEND _header "#pragma once\n\n")
    string(APPEND _header "static const char * const JLLAMA_JAVA_CLI_FLAGS[] = {\n${_body}};\n\n")
    string(APPEND _header "static const int JLLAMA_JAVA_CLI_FLAG_COUNT = ${_count};\n")

    # Only rewrite when the content actually changed, so an unrelated re-configure does not
    # touch the header and force a needless rebuild of the test.
    set(_existing "")
    if(EXISTS "${ARG_OUTPUT_HEADER}")
        file(READ "${ARG_OUTPUT_HEADER}" _existing)
    endif()
    if(NOT _existing STREQUAL _header)
        file(WRITE "${ARG_OUTPUT_HEADER}" "${_header}")
    endif()

    # Re-run configure (and therefore this extractor) whenever a scanned Java file changes.
    foreach(_src IN LISTS ARG_JAVA_FLAG_SOURCES)
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${_src}")
    endforeach()

    message(STATUS "jllama: extracted ${_count} Java CLI flags -> ${ARG_OUTPUT_HEADER}")
endfunction()
