// SPDX-FileCopyrightText: 2026 Bernard Ladenthin <bernard.ladenthin@gmail.com>
//
// SPDX-License-Identifier: MIT

package net.ladenthin.llama;

import com.fasterxml.jackson.databind.JsonNode;

/**
 * Per-completion timing data parsed from a llama.cpp result {@code timings} block.
 * <p>
 * The native {@code result_timings::to_json()} emits these fields:
 * {@code cache_n}, {@code prompt_n}, {@code prompt_ms}, {@code prompt_per_token_ms},
 * {@code prompt_per_second}, {@code predicted_n}, {@code predicted_ms},
 * {@code predicted_per_token_ms}, {@code predicted_per_second}. Speculative-decoding
 * runs additionally include {@code draft_n} and {@code draft_n_accepted}.
 * </p>
 */
public final class Timings {

    private final int cacheN;
    private final int promptN;
    private final double promptMs;
    private final double promptPerSecond;
    private final int predictedN;
    private final double predictedMs;
    private final double predictedPerSecond;
    private final int draftN;
    private final int draftNAccepted;

    public Timings(int cacheN, int promptN, double promptMs, double promptPerSecond,
                   int predictedN, double predictedMs, double predictedPerSecond,
                   int draftN, int draftNAccepted) {
        this.cacheN = cacheN;
        this.promptN = promptN;
        this.promptMs = promptMs;
        this.promptPerSecond = promptPerSecond;
        this.predictedN = predictedN;
        this.predictedMs = predictedMs;
        this.predictedPerSecond = predictedPerSecond;
        this.draftN = draftN;
        this.draftNAccepted = draftNAccepted;
    }

    /**
     * Parse a {@link Timings} from a JSON object matching the native {@code timings} block.
     * Missing fields default to {@code 0}.
     *
     * @param node the {@code timings} object node; may be a missing-node
     * @return a populated {@link Timings} (all-zero when {@code node} is missing/null)
     */
    public static Timings fromJson(JsonNode node) {
        if (node == null || node.isMissingNode() || node.isNull()) {
            return new Timings(0, 0, 0.0, 0.0, 0, 0.0, 0.0, 0, 0);
        }
        return new Timings(
                node.path("cache_n").asInt(0),
                node.path("prompt_n").asInt(0),
                node.path("prompt_ms").asDouble(0.0),
                node.path("prompt_per_second").asDouble(0.0),
                node.path("predicted_n").asInt(0),
                node.path("predicted_ms").asDouble(0.0),
                node.path("predicted_per_second").asDouble(0.0),
                node.path("draft_n").asInt(0),
                node.path("draft_n_accepted").asInt(0));
    }

    /** Number of tokens served from the KV cache without re-evaluation. */
    public int getCacheN() {
        return cacheN;
    }

    /** Number of prompt tokens processed. */
    public int getPromptN() {
        return promptN;
    }

    /** Wall-clock milliseconds spent processing the prompt. */
    public double getPromptMs() {
        return promptMs;
    }

    /** Prompt tokens per second throughput. */
    public double getPromptPerSecond() {
        return promptPerSecond;
    }

    /** Number of tokens generated. */
    public int getPredictedN() {
        return predictedN;
    }

    /** Wall-clock milliseconds spent generating tokens. */
    public double getPredictedMs() {
        return predictedMs;
    }

    /** Generated tokens per second throughput. */
    public double getPredictedPerSecond() {
        return predictedPerSecond;
    }

    /**
     * Number of draft tokens generated by the speculative engine.
     * Zero when speculative decoding was not active.
     */
    public int getDraftN() {
        return draftN;
    }

    /**
     * Number of draft tokens accepted by the target model.
     * Zero when speculative decoding was not active.
     */
    public int getDraftNAccepted() {
        return draftNAccepted;
    }

    @Override
    public String toString() {
        return "Timings{cacheN=" + cacheN
                + ", promptN=" + promptN + ", promptMs=" + promptMs
                + ", promptPerSecond=" + promptPerSecond
                + ", predictedN=" + predictedN + ", predictedMs=" + predictedMs
                + ", predictedPerSecond=" + predictedPerSecond
                + ", draftN=" + draftN + ", draftNAccepted=" + draftNAccepted + "}";
    }
}
